DataBase:
  Host: localhost
  Port: 3306
  User: root
  Password: F
  NameDB: Kray
  SqlitePath: Kry.db
  Engine: sqlite
Server:
  Ip: 127.0.0.1
  Port: 8000
  Debug: true
  ServerSave: 9
  LengthSecurity: 128
Access:
  AprovedTodays: 3
Email:
  SmtpUsername: "no-reply@lostrespinos.cl"
  Password: "maumau123"
  SmptPort: "465"
  SmtpServer: "mail.lostrespinos.cl"