DataBase:
  Host: www.ainhosoft.cl
  Port: 3306
  User: mau
  Password: Fcua29hd.8orda4p2
  NameDB: Kray
  SqlitePath: Kry.db
  Engine: sqlite
Server:
  Ip: 127.0.0.1
  Port: 8000
  Debug: true
  LengthSecurity: 128
Access:
  AprovedTodays: 3

Email:
  SmtpUserName: ""
  Password: ""
  SmtpPort: 465
  SmtpServer: ""
